### ISSUE TITLE
What is the difference between Type 2 and Type 1?

### ISSUE THREAD

**Issue by SYancun** [EoghanONeill/TobitBART#1]
I am trying to modify Tobit type 2 to perform a regression prediction on data with censor_labels but no fixed censored_below and censored_above. I am unsure if this is theoretically feasible and whether the author has considered publishing a type 2 paper on this topic.

**Comment by EoghanONeill** [comment]
Type 1 is not applicable if there is no censored_below or censored_above. It might be feasible to edit the code if there are observation-specific thresholds.
Type 2 tobit is a sample selection model and perhaps is the type that you require. Type 2 has no fixed censoring threshold. Different variables can determine selection (i.e. whether a variable is observed or not) and the outcome values. The type 2 model also accounts for selection on unobservables under the assumption of joint normality.

I am working on a Type 2 TOBART paper similar to the type I TOBART paper.

Both the type 1 and type 2 functions are works in progress. ``tbart1()`` seems to work as intended. I plan to carry out more testing and MCMC diagnostics for ``tbart1np()``, which models the error as a Dirichlet Process mixture of normal distributions.

``tbart2c()`` and ``tbart2np()`` are type 2 TOBART with, respectively, jointly normally distributed errors and a Dirichlet Process Mixture of joint normal distributions for the errors, but these functions might contain bugs and require more testing.

Thank you for your interest in this package.
